name: hoteque_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  http: ^1.3.0
  equatable: ^2.0.7
  http_parser: ^4.1.2
  flutter_native_splash: ^2.4.6
  intl: ^0.20.2
  flutter_svg: ^2.1.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/logo-hotelqu.png
  color_dark: "#121212"
  image_dark: assets/icon/logo-hotelqu.png

  android_12:
    image: assets/icon/logo-hotelqu.png
    icon_background_color: "#ffffff"
    image_dark: assets/icon/logo-hotelqu.png
    icon_background_color_dark: "#121212"

  web: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/quicksand/Quicksand-Bold.ttf
          weight: 700
        - asset: fonts/quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: fonts/quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: fonts/quicksand/Quicksand-Light.ttf
          weight: 300
